// <auto-generated />
using System;
using ComunaHealth.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ComunaHealth.Migrations
{
    [DbContext(typeof(ComunaDbContext))]
    [Migration("20211003234030_prueba")]
    partial class prueba
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ComunaHealth.Modelos.ModeloChat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaveEncriptado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("GuidChat")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("PuedeSerModificado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("ComunaHealth.Modelos.ModeloCita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Duracion")
                        .HasColumnType("int");

                    b.Property<int>("EspecializacionCita")
                        .HasColumnType("int");

                    b.Property<int>("EstadoCita")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("ModeloCita");
                });

            modelBuilder.Entity("ComunaHealth.Modelos.ModeloContenedorDeEntradas<ComunaHealth.Modelos.ModeloEntrada>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaveEncriptado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("PuedeSerModificado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ModeloContenedorDeEntradas<ModeloEntrada>");
                });

            modelBuilder.Entity("ComunaHealth.Modelos.ModeloContenedorDeEntradas<ComunaHealth.Modelos.ModeloEntradaHistorialMedico>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaveEncriptado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("PuedeSerModificado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ModeloContenedorDeEntradas<ModeloEntradaHistorialMedico>");
                });

            modelBuilder.Entity("ComunaHealth.Modelos.ModeloEntrada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Contenido")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("FechaDeCreacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModeloContenedorDeEntradas<ModeloEntrada>Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModeloContenedorDeEntradas<ModeloEntrada>Id");

                    b.ToTable("ModeloEntrada");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ModeloEntrada");
                });

            modelBuilder.Entity("ComunaHealth.Modelos.ModeloRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EspecializacionRepresentada")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("ComunaHealth.Modelos.ModeloSolicitudCambioHorarioDeCita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NuevaDuracion")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("NuevaFecha")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Razon")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("ModeloSolicitudCambioHorarioDeCita");
                });

            modelBuilder.Entity("ComunaHealth.Modelos.ModeloUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DNI")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("EstadoCuenta")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StringTiposCuenta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TiposCuenta");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasAlternateKey("DNI");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ModeloUsuario");
                });

            modelBuilder.Entity("ComunaHealth.Relaciones.TICitaMedico", b =>
                {
                    b.Property<int>("IdCita")
                        .HasColumnType("int");

                    b.Property<int>("IdMedico")
                        .HasColumnType("int");

                    b.HasKey("IdCita", "IdMedico");

                    b.HasIndex("IdCita")
                        .IsUnique();

                    b.HasIndex("IdMedico");

                    b.ToTable("TICitaMedico");
                });

            modelBuilder.Entity("ComunaHealth.Relaciones.TICitaPaciente", b =>
                {
                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<int>("IdCita")
                        .HasColumnType("int");

                    b.HasKey("IdPaciente", "IdCita");

                    b.HasIndex("IdCita")
                        .IsUnique();

                    b.ToTable("TICitaPaciente");
                });

            modelBuilder.Entity("ComunaHealth.Relaciones.TICitaSolicitudCambioHorarioCita", b =>
                {
                    b.Property<int>("IdSolicitudCambioHorarioDeCita")
                        .HasColumnType("int");

                    b.Property<int>("IdCita")
                        .HasColumnType("int");

                    b.HasKey("IdSolicitudCambioHorarioDeCita", "IdCita");

                    b.HasIndex("IdCita")
                        .IsUnique();

                    b.HasIndex("IdSolicitudCambioHorarioDeCita")
                        .IsUnique();

                    b.ToTable("TICitaSolicitudCambioHorarioCita");
                });

            modelBuilder.Entity("ComunaHealth.Relaciones.TIMedicoContenedorEntrada", b =>
                {
                    b.Property<int>("IdMedico")
                        .HasColumnType("int");

                    b.Property<int>("IdEntrada")
                        .HasColumnType("int");

                    b.HasKey("IdMedico", "IdEntrada");

                    b.HasIndex("IdEntrada");

                    b.ToTable("TIMedicoContenedorEntrada");
                });

            modelBuilder.Entity("ComunaHealth.Relaciones.TIMedicoContenedorEntradaHistorialMedico", b =>
                {
                    b.Property<int>("IdMedico")
                        .HasColumnType("int");

                    b.Property<int>("IdEntradaHistorialMedico")
                        .HasColumnType("int");

                    b.HasKey("IdMedico", "IdEntradaHistorialMedico");

                    b.HasIndex("IdEntradaHistorialMedico");

                    b.ToTable("TIMedicoContenedorEntradaHistorialMedico");
                });

            modelBuilder.Entity("ComunaHealth.Relaciones.TIPacienteContenedorEntrada", b =>
                {
                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<int>("IdContenedorEntrada")
                        .HasColumnType("int");

                    b.HasKey("IdPaciente", "IdContenedorEntrada");

                    b.HasIndex("IdContenedorEntrada");

                    b.ToTable("TIPacienteContenedorEntrada");
                });

            modelBuilder.Entity("ComunaHealth.Relaciones.TIPacienteContenedorEntradaCambiosEstiloVida", b =>
                {
                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<int>("IdContenedorEntrada")
                        .HasColumnType("int");

                    b.HasKey("IdPaciente", "IdContenedorEntrada");

                    b.HasIndex("IdContenedorEntrada");

                    b.ToTable("TIPacienteContenedorEntradaCambiosEstiloVida");
                });

            modelBuilder.Entity("ComunaHealth.Relaciones.TIPacienteContenedorEntradaHistorialMedico", b =>
                {
                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<int>("IdEntradaHistorialMedico")
                        .HasColumnType("int");

                    b.HasKey("IdPaciente", "IdEntradaHistorialMedico");

                    b.HasIndex("IdEntradaHistorialMedico");

                    b.ToTable("TIPacienteContenedorEntradaHistorialMedico");
                });

            modelBuilder.Entity("ComunaHealth.Relaciones.TIUsuarioNoAdministradorSolicitudCambioHorarioCita", b =>
                {
                    b.Property<int>("IdSolicitudPostergacionCita")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioNoAdministrador")
                        .HasColumnType("int");

                    b.HasKey("IdSolicitudPostergacionCita", "IdUsuarioNoAdministrador");

                    b.HasIndex("IdSolicitudPostergacionCita")
                        .IsUnique();

                    b.HasIndex("IdUsuarioNoAdministrador");

                    b.ToTable("TIUsuarioNoAdministradorSolicitudCambioHorarioCita");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:Identity", "(1, 1)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IdentityUser<int>");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ModeloChatModeloUsuario", b =>
                {
                    b.Property<int>("ChatsId")
                        .HasColumnType("int");

                    b.Property<int>("ParticipantesId")
                        .HasColumnType("int");

                    b.HasKey("ChatsId", "ParticipantesId");

                    b.HasIndex("ParticipantesId");

                    b.ToTable("ModeloChatModeloUsuario");
                });

            modelBuilder.Entity("ModeloMedicoModeloPaciente", b =>
                {
                    b.Property<int>("MedicosId")
                        .HasColumnType("int");

                    b.Property<int>("PacientesId")
                        .HasColumnType("int");

                    b.HasKey("MedicosId", "PacientesId");

                    b.HasIndex("PacientesId");

                    b.ToTable("ModeloMedicoModeloPaciente");
                });

            modelBuilder.Entity("ComunaHealth.Modelos.ModeloEntradaHistorialMedico", b =>
                {
                    b.HasBaseType("ComunaHealth.Modelos.ModeloEntrada");

                    b.Property<int>("Especializacion")
                        .HasColumnType("int");

                    b.Property<int?>("MedicoCreadorId")
                        .HasColumnType("int");

                    b.Property<int?>("ModeloContenedorDeEntradas<ModeloEntradaHistorialMedico>Id")
                        .HasColumnType("int");

                    b.Property<int?>("PacienteId")
                        .HasColumnType("int");

                    b.HasIndex("MedicoCreadorId");

                    b.HasIndex("ModeloContenedorDeEntradas<ModeloEntradaHistorialMedico>Id");

                    b.HasIndex("PacienteId");

                    b.HasDiscriminator().HasValue("ModeloEntradaHistorialMedico");
                });

            modelBuilder.Entity("ComunaHealth.Modelos.ModeloMensajeChat", b =>
                {
                    b.HasBaseType("ComunaHealth.Modelos.ModeloEntrada");

                    b.Property<int?>("ModeloChatId")
                        .HasColumnType("int");

                    b.Property<int?>("RemitenteId")
                        .HasColumnType("int");

                    b.HasIndex("ModeloChatId");

                    b.HasIndex("RemitenteId");

                    b.HasDiscriminator().HasValue("ModeloMensajeChat");
                });

            modelBuilder.Entity("ComunaHealth.Modelos.ModeloAdministrador", b =>
                {
                    b.HasBaseType("ComunaHealth.Modelos.ModeloUsuario");

                    b.Property<int>("RegionSanitaria")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("ModeloAdministrador");
                });

            modelBuilder.Entity("ComunaHealth.Modelos.ModeloUsuarioNoAdministrador", b =>
                {
                    b.HasBaseType("ComunaHealth.Modelos.ModeloUsuario");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("FotoAnversoDNI")
                        .IsRequired()
                        .HasColumnType("image");

                    b.Property<byte[]>("FotoDePerfil")
                        .HasColumnType("image");

                    b.Property<byte[]>("FotoReversoDNI")
                        .IsRequired()
                        .HasColumnType("image");

                    b.Property<bool>("MailEsPublico")
                        .HasColumnType("bit");

                    b.Property<int>("Municipio")
                        .HasColumnType("int");

                    b.Property<bool?>("TelefonoEsPublico")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("ModeloUsuarioNoAdministrador");
                });

            modelBuilder.Entity("ComunaHealth.Modelos.Identity.Usuarios.ModeloAdministradorJefe", b =>
                {
                    b.HasBaseType("ComunaHealth.Modelos.ModeloAdministrador");

                    b.HasDiscriminator().HasValue("ModeloAdministradorJefe");
                });

            modelBuilder.Entity("ComunaHealth.Modelos.ModeloMedico", b =>
                {
                    b.HasBaseType("ComunaHealth.Modelos.ModeloUsuarioNoAdministrador");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StringEspecializaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Especializaciones");

                    b.HasDiscriminator().HasValue("ModeloMedico");
                });

            modelBuilder.Entity("ComunaHealth.Modelos.ModeloPaciente", b =>
                {
                    b.HasBaseType("ComunaHealth.Modelos.ModeloUsuarioNoAdministrador");

                    b.HasDiscriminator().HasValue("ModeloPaciente");
                });

            modelBuilder.Entity("ComunaHealth.Modelos.ModeloEntrada", b =>
                {
                    b.HasOne("ComunaHealth.Modelos.ModeloContenedorDeEntradas<ComunaHealth.Modelos.ModeloEntrada>", null)
                        .WithMany("Entradas")
                        .HasForeignKey("ModeloContenedorDeEntradas<ModeloEntrada>Id");
                });

            modelBuilder.Entity("ComunaHealth.Relaciones.TICitaMedico", b =>
                {
                    b.HasOne("ComunaHealth.Modelos.ModeloCita", "Cita")
                        .WithOne("Medico")
                        .HasForeignKey("ComunaHealth.Relaciones.TICitaMedico", "IdCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComunaHealth.Modelos.ModeloMedico", "Medico")
                        .WithMany("Citas")
                        .HasForeignKey("IdMedico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("ComunaHealth.Relaciones.TICitaPaciente", b =>
                {
                    b.HasOne("ComunaHealth.Modelos.ModeloCita", "Cita")
                        .WithOne("Paciente")
                        .HasForeignKey("ComunaHealth.Relaciones.TICitaPaciente", "IdCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComunaHealth.Modelos.ModeloPaciente", "Paciente")
                        .WithMany("Citas")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ComunaHealth.Relaciones.TICitaSolicitudCambioHorarioCita", b =>
                {
                    b.HasOne("ComunaHealth.Modelos.ModeloCita", "Cita")
                        .WithOne("SolicitudCambioHorario")
                        .HasForeignKey("ComunaHealth.Relaciones.TICitaSolicitudCambioHorarioCita", "IdCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComunaHealth.Modelos.ModeloSolicitudCambioHorarioDeCita", "SolicitudCambioHorarioDeCita")
                        .WithOne("Cita")
                        .HasForeignKey("ComunaHealth.Relaciones.TICitaSolicitudCambioHorarioCita", "IdSolicitudCambioHorarioDeCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");

                    b.Navigation("SolicitudCambioHorarioDeCita");
                });

            modelBuilder.Entity("ComunaHealth.Relaciones.TIMedicoContenedorEntrada", b =>
                {
                    b.HasOne("ComunaHealth.Modelos.ModeloContenedorDeEntradas<ComunaHealth.Modelos.ModeloEntrada>", "Entrada")
                        .WithMany()
                        .HasForeignKey("IdEntrada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComunaHealth.Modelos.ModeloMedico", "Medico")
                        .WithMany("Notas")
                        .HasForeignKey("IdMedico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entrada");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("ComunaHealth.Relaciones.TIMedicoContenedorEntradaHistorialMedico", b =>
                {
                    b.HasOne("ComunaHealth.Modelos.ModeloContenedorDeEntradas<ComunaHealth.Modelos.ModeloEntradaHistorialMedico>", "EntradaHistorialMedico")
                        .WithMany()
                        .HasForeignKey("IdEntradaHistorialMedico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComunaHealth.Modelos.ModeloMedico", "Medico")
                        .WithMany("NotasPacientes")
                        .HasForeignKey("IdMedico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntradaHistorialMedico");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("ComunaHealth.Relaciones.TIPacienteContenedorEntrada", b =>
                {
                    b.HasOne("ComunaHealth.Modelos.ModeloContenedorDeEntradas<ComunaHealth.Modelos.ModeloEntrada>", "ContenedorEntrada")
                        .WithMany()
                        .HasForeignKey("IdContenedorEntrada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComunaHealth.Modelos.ModeloPaciente", "Paciente")
                        .WithMany("Diario")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContenedorEntrada");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ComunaHealth.Relaciones.TIPacienteContenedorEntradaCambiosEstiloVida", b =>
                {
                    b.HasOne("ComunaHealth.Modelos.ModeloContenedorDeEntradas<ComunaHealth.Modelos.ModeloEntrada>", "ContenedorEntrada")
                        .WithMany()
                        .HasForeignKey("IdContenedorEntrada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComunaHealth.Modelos.ModeloPaciente", "Paciente")
                        .WithMany("CambiosEstiloDeVida")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContenedorEntrada");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ComunaHealth.Relaciones.TIPacienteContenedorEntradaHistorialMedico", b =>
                {
                    b.HasOne("ComunaHealth.Modelos.ModeloContenedorDeEntradas<ComunaHealth.Modelos.ModeloEntradaHistorialMedico>", "EntradaHistorialMedico")
                        .WithMany()
                        .HasForeignKey("IdEntradaHistorialMedico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComunaHealth.Modelos.ModeloPaciente", "Paciente")
                        .WithMany("HistorialMedico")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntradaHistorialMedico");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ComunaHealth.Relaciones.TIUsuarioNoAdministradorSolicitudCambioHorarioCita", b =>
                {
                    b.HasOne("ComunaHealth.Modelos.ModeloSolicitudCambioHorarioDeCita", "SolicitudPostergacionCita")
                        .WithOne("Solicitante")
                        .HasForeignKey("ComunaHealth.Relaciones.TIUsuarioNoAdministradorSolicitudCambioHorarioCita", "IdSolicitudPostergacionCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComunaHealth.Modelos.ModeloUsuarioNoAdministrador", "UsuarioNoAdministrador")
                        .WithMany()
                        .HasForeignKey("IdUsuarioNoAdministrador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolicitudPostergacionCita");

                    b.Navigation("UsuarioNoAdministrador");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("ComunaHealth.Modelos.ModeloRol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("ComunaHealth.Modelos.ModeloUsuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("ComunaHealth.Modelos.ModeloUsuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("ComunaHealth.Modelos.ModeloRol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComunaHealth.Modelos.ModeloUsuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("ComunaHealth.Modelos.ModeloUsuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModeloChatModeloUsuario", b =>
                {
                    b.HasOne("ComunaHealth.Modelos.ModeloChat", null)
                        .WithMany()
                        .HasForeignKey("ChatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComunaHealth.Modelos.ModeloUsuario", null)
                        .WithMany()
                        .HasForeignKey("ParticipantesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModeloMedicoModeloPaciente", b =>
                {
                    b.HasOne("ComunaHealth.Modelos.ModeloMedico", null)
                        .WithMany()
                        .HasForeignKey("MedicosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComunaHealth.Modelos.ModeloPaciente", null)
                        .WithMany()
                        .HasForeignKey("PacientesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ComunaHealth.Modelos.ModeloEntradaHistorialMedico", b =>
                {
                    b.HasOne("ComunaHealth.Modelos.ModeloMedico", "MedicoCreador")
                        .WithMany()
                        .HasForeignKey("MedicoCreadorId");

                    b.HasOne("ComunaHealth.Modelos.ModeloContenedorDeEntradas<ComunaHealth.Modelos.ModeloEntradaHistorialMedico>", null)
                        .WithMany("Entradas")
                        .HasForeignKey("ModeloContenedorDeEntradas<ModeloEntradaHistorialMedico>Id");

                    b.HasOne("ComunaHealth.Modelos.ModeloPaciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId");

                    b.Navigation("MedicoCreador");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ComunaHealth.Modelos.ModeloMensajeChat", b =>
                {
                    b.HasOne("ComunaHealth.Modelos.ModeloChat", null)
                        .WithMany("Entradas")
                        .HasForeignKey("ModeloChatId");

                    b.HasOne("ComunaHealth.Modelos.ModeloUsuario", "Remitente")
                        .WithMany()
                        .HasForeignKey("RemitenteId");

                    b.Navigation("Remitente");
                });

            modelBuilder.Entity("ComunaHealth.Modelos.ModeloChat", b =>
                {
                    b.Navigation("Entradas");
                });

            modelBuilder.Entity("ComunaHealth.Modelos.ModeloCita", b =>
                {
                    b.Navigation("Medico")
                        .IsRequired();

                    b.Navigation("Paciente")
                        .IsRequired();

                    b.Navigation("SolicitudCambioHorario");
                });

            modelBuilder.Entity("ComunaHealth.Modelos.ModeloContenedorDeEntradas<ComunaHealth.Modelos.ModeloEntrada>", b =>
                {
                    b.Navigation("Entradas");
                });

            modelBuilder.Entity("ComunaHealth.Modelos.ModeloContenedorDeEntradas<ComunaHealth.Modelos.ModeloEntradaHistorialMedico>", b =>
                {
                    b.Navigation("Entradas");
                });

            modelBuilder.Entity("ComunaHealth.Modelos.ModeloSolicitudCambioHorarioDeCita", b =>
                {
                    b.Navigation("Cita")
                        .IsRequired();

                    b.Navigation("Solicitante")
                        .IsRequired();
                });

            modelBuilder.Entity("ComunaHealth.Modelos.ModeloMedico", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("Notas");

                    b.Navigation("NotasPacientes");
                });

            modelBuilder.Entity("ComunaHealth.Modelos.ModeloPaciente", b =>
                {
                    b.Navigation("CambiosEstiloDeVida");

                    b.Navigation("Citas");

                    b.Navigation("Diario");

                    b.Navigation("HistorialMedico");
                });
#pragma warning restore 612, 618
        }
    }
}
